In [4]:
import pandas as pd 
import numpy as np 

In [2]:
data = pd.read_csv("Costomer+OrderForm.csv")
data

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [14]:
data = pd.get_dummies(data)

In [15]:
array = np.array(data)

In [16]:
from scipy.stats import chi2_contingency

chi2, p_value , dof, expected = chi2_contingency(array)

In [17]:
print("Chi-square statistic:", chi2)
print("P-value:", p_value)
print("Degrees of freedom:", dof)
print("Expected frequencies table:")
print(expected)

Chi-square statistic: 1200.0
P-value: 1.0
Degrees of freedom: 2093
Expected frequencies table:
[[0.09666667 0.90333333 0.11       ... 0.89666667 0.06666667 0.93333333]
 [0.09666667 0.90333333 0.11       ... 0.89666667 0.06666667 0.93333333]
 [0.09666667 0.90333333 0.11       ... 0.89666667 0.06666667 0.93333333]
 ...
 [0.09666667 0.90333333 0.11       ... 0.89666667 0.06666667 0.93333333]
 [0.09666667 0.90333333 0.11       ... 0.89666667 0.06666667 0.93333333]
 [0.09666667 0.90333333 0.11       ... 0.89666667 0.06666667 0.93333333]]


In [20]:
if p_value < 0.05:
    print("Reject the null hypothesis. There is a significant difference.")
else:
    print("Fail to reject the null hypothesis. No significant difference.")

Fail to reject the null hypothesis. No significant difference.
